[package]
name = "super-mastermind"
version = "0.1.0"
authors = ["barder60 <kaderate.yamamoto@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
